"""sales person FK added in samples

Revision ID: 1da333ba2818
Revises: 63cd0dc22062
Create Date: 2026-05-05 11:39:09.134835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da333ba2818'
down_revision = '63cd0dc22062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_person_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sales_person_name', sa.String(length=120), nullable=True))
        batch_op.create_foreign_key(None, 'salespersons', ['sales_person_id'], ['id'])
        batch_op.drop_column('sales_person')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_person', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sales_person_name')
        batch_op.drop_column('sales_person_id')

    # ### end Alembic commands ###
