"""added status completed_at remarks to samples

Revision ID: 7939c2305245
Revises: 1da333ba2818
Create Date: 2026-05-06 11:53:36.936646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7939c2305245'
down_revision = '1da333ba2818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('salesperson_remark', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('shushil_remark', sa.Text(), nullable=True))
        batch_op.alter_column('order_received_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.alter_column('order_received_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
        batch_op.drop_column('shushil_remark')
        batch_op.drop_column('salesperson_remark')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
