"""initial migration

Revision ID: 7aca862ea1f9
Revises: 
Create Date: 2026-05-04 16:15:36.062959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aca862ea1f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('is_moradabad', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_code', sa.String(length=50), nullable=False),
    sa.Column('party_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('party_code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_person', sa.String(length=120), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('party_name_direct', sa.String(length=200), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('order_received_date', sa.Date(), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sample_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.String(length=100), nullable=False),
    sa.Column('matched_with', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_product_id', sa.Integer(), nullable=False),
    sa.Column('order_yes_no', sa.Boolean(), nullable=True),
    sa.Column('quantity_kg', sa.Float(), nullable=True),
    sa.Column('total_order_qty', sa.Float(), nullable=True),
    sa.Column('filled_by', sa.Integer(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['filled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sample_product_id'], ['sample_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_details')
    op.drop_table('sample_products')
    op.drop_table('samples')
    op.drop_table('users')
    op.drop_table('parties')
    op.drop_table('cities')
    # ### end Alembic commands ###
