"""added phone number and name of sales person in party table

Revision ID: 95289b224e24
Revises: 7aca862ea1f9
Create Date: 2026-05-05 10:36:29.927937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95289b224e24'
down_revision = '7aca862ea1f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sales_person_name', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.drop_column('sales_person_name')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
