"""added salesperson_id to users

Revision ID: b62f6b9a8b49
Revises: 7939c2305245
Create Date: 2026-05-06 13:49:16.852340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b62f6b9a8b49'
down_revision = '7939c2305245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salesperson_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'salespersons', ['salesperson_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('salesperson_id')

    # ### end Alembic commands ###
